server:
  port: 9002

spring:
  security:
    oauth2:
      client:
        registration:
          line:
            provider:                     "line"
            client-name:                  "Line"
            client-id:                    "[env]"
            client-secret:                "[env]"
            redirect-uri:                 "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type:     "authorization_code"
            client-authentication-method: "POST"
        provider:
          line:
            authorization-uri: "https://access.line.me/dialog/oauth/weblogin"
            token-uri:         "https://api.line.me/v1/oauth/accessToken"
            user-info-uri:     "https://api.line.me/v2/profile"
            user-info-authentication-method: "get"
            user-name-attribute: "id" 

logging:
  level:
    org.springframework.web.client.RestTemplate:  DEBUG
    org.springframework.security.access: DEBUG

