server:
  port: 9002
  ssl:
    key-store:          "classpath:keystore.p12"
    key-store-password: "12345678"
    key-store-type:     "PKCS12"
    key-alias:          "tomcat"

spring:
  security:
    oauth2:
      client:
        registration:
          line:
            provider:                     "line"
            client-name:                  "Line"
            
            client-id:                    "[env]"
            client-secret:                "[env]"
            redirect-uri:                 "{baseUrl}/login/oauth2/code/{registrationId}"
            
            authorization-grant-type:     "authorization_code"
            client-authentication-method: "POST"
            
        provider:
          line:
            authorization-uri: "https://access.line.me/dialog/oauth/weblogin"
            token-uri:         "https://api.line.me/v2/oauth/accessToken"
            user-info-uri:     "https://api.line.me/v2/profile"
            user-info-authentication-method: "get"
            user-name-attribute: "userId" 

logging:
  level:
    com.example: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG 

